{
  "hash": "992ff906c7515dbacb675d7dae81c81e",
  "result": {
    "markdown": "---\ntitle: \"Probability Theory\"\n---\n\n\nThis section introduced the basics of probability theory.\n\n# Assignment\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-1_9e9410dea57b66a671b3f644a3d4d164'}\n\n```{.r .cell-code}\nrm(list = ls())\n\nscope <- 0.3;\nnScope <- 0.7;\n\ntimeScope <- 0.2;\nnTimeScope <- 0.8;\n\ntimeNScope <- 0.6;\nnTimeNScope <- 0.4;\n\np1 <- scope * timeScope\np2 <- scope * nTimeScope\np3 <- nScope * timeNScope\np4 <- nScope * nTimeNScope\n\nsum <- p1+p2+p3+p4\n```\n:::\n\n\n$$ P(T \\cap S) $$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-2_82370339ab07c33c2e6f885f01890c17'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.06\n```\n:::\n:::\n\n\n$$ P(T \\cap \\bar{S})$$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-3_502d5efb73461795e0ee5f1cd642e11c'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.24\n```\n:::\n:::\n\n$$ P(\\bar{T} \\cap S)$$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-4_82c2e95d36aabd00c8f04fbaf37d8ccd'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.42\n```\n:::\n:::\n\n$$ P(\\bar{T} \\cap \\bar{S})$$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-5_551cfb9220a8ef87725f5737e45a40cf'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.28\n```\n:::\n:::\n\n**SUM**\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-6_d33f4bd9b1c73a3bf95181617c97ce08'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1\n```\n:::\n:::\n\n\n# Assignment\n\nAll three = 0.5% or 5 people.\nAt least two = 8.8% + 7.3% + 3.3% => 19.4% or 194 people.\nOnly one = 10% + 27.8% + 42.3% => 80.1% or 801 people.\n\n# Assignment\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-7_1309aea8defb7efde108b552f598eefe'}\n\n```{.r .cell-code}\npBA <- 0.97\npBnA <- 0.01\npA <- 0.04\npnA <- 0.96\n\npnAB <- (pBnA*pnA)/(pBA*pA+pBnA*pnA)\n\npAB <- (pBA*pA)/(pBA*pA+pBnA*pnA)\n```\n:::\n\n\n$$P(\\bar{A}|B)$$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-8_c6c4181eecb087481e7a2dd9efb5e5e1'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.1983471\n```\n:::\n:::\n\n\n$$P(A|B)$$\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-9_93afb6aa7adadb11ee6b891ced44bf54'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.8016529\n```\n:::\n:::\n\n\nThese results show that in case the alarm is triggered, \nthere is a possibility of about 19.83% (pnAB) that the product is flawless \nand a probability of 80.165% (pAB) that the product is faulty.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}