{
  "hash": "3e532fc9e4b684e90de68d363430d689",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\nThis section will introduce an option to graphically represent the relationship between \ndifferent variables with the help of **directed acylic graphs (DAGs)**\n\n# Display parking spot example\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_313a71ff150d3216828dff0c1032e97a'}\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nAs one can see the location influences the number of available spots and sales, while spots also influences the sales\n\n# Computing relevant values of data set *costumer_sat.rds*\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_22cbddab3c43221824f14360cc6022bc'}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"follow_ups\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"satisfaction\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"subscription\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"8\",\"2\":\"40\",\"3\":\"Elite\"},{\"1\":\"7\",\"2\":\"45\",\"3\":\"Elite\"},{\"1\":\"8\",\"2\":\"47\",\"3\":\"Elite\"},{\"1\":\"9\",\"2\":\"44\",\"3\":\"Elite\"},{\"1\":\"10\",\"2\":\"50\",\"3\":\"Elite\"},{\"1\":\"6\",\"2\":\"55\",\"3\":\"Premium+\"},{\"1\":\"7\",\"2\":\"60\",\"3\":\"Premium+\"},{\"1\":\"6\",\"2\":\"62\",\"3\":\"Premium+\"},{\"1\":\"8\",\"2\":\"59\",\"3\":\"Premium+\"},{\"1\":\"8\",\"2\":\"65\",\"3\":\"Premium+\"},{\"1\":\"0\",\"2\":\"70\",\"3\":\"Premium\"},{\"1\":\"1\",\"2\":\"74\",\"3\":\"Premium\"},{\"1\":\"2\",\"2\":\"77\",\"3\":\"Premium\"},{\"1\":\"2\",\"2\":\"74\",\"3\":\"Premium\"},{\"1\":\"3\",\"2\":\"80\",\"3\":\"Premium\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Regress *satisfaction* on *follow_ups*\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_590c0c41d4f9d1136148d39b3ca287ce'}\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n\n## Regress *satisfaction* on *follow_ups* and account for *subscription*\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_a925d9f66d74d8643e21f1f61afaedb4'}\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n# Compare the coefficients\n\n**Satisfaction on follow_ups**\n\nm1 = -3.3093 b = 78.886\n\n**Satisfaction on follow_ups and account for subscription**\n\nm1 = 2.1944 m2 = 44.7222 m3 = 18.0722 b = 26.7667\n\nExplanation: As the satisfaction decreases, if the data is not conditioned \non subscription, but at the same time increases, if conditioned on subscription\nyou can assume that the subscription has an negative impact on the satisfaction\nThis can have multiple explanations, maybe the product is to expensive or\nthe amount of functions to overwhelming.\n\n# Plot data\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_ad652cc06461dc2e0ba6cbf4a13593dd'}\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nAs one can see that if the subscription is accounted for, the satisfaction increases for all subscription tiers if the support does a follow up.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}