{
  "hash": "717bb9b477b3cd53a1304714e237e18c",
  "result": {
    "markdown": "---\ntitle: \"Regression and Statistical Inference\"\n---\n\n\nThis section is about regression. Regression is used to examine and explain the relationship\nbetween different variables.\n\nFor the assignments the following data was used.\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-1_8b37ee75b2ee275dc790a07a8ae4ce80'}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"aspiration\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"doornumber\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"carbody\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"drivewheel\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginelocation\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"wheelbase\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carlength\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carwidth\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carheight\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"curbweight\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"enginetype\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cylindernumber\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"enginesize\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"fuelsystem\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"boreratio\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stroke\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"compressionratio\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"horsepower\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"peakrpm\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"citympg\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"highwaympg\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"price\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.00\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"13495.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"88.6\",\"7\":\"168.8\",\"8\":\"64.1\",\"9\":\"48.8\",\"10\":\"2548\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.47\",\"16\":\"2.68\",\"17\":\"9.00\",\"18\":\"111\",\"19\":\"5000\",\"20\":\"21\",\"21\":\"27\",\"22\":\"16500.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"171.2\",\"8\":\"65.5\",\"9\":\"52.4\",\"10\":\"2823\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"152\",\"14\":\"mpfi\",\"15\":\"2.68\",\"16\":\"3.47\",\"17\":\"9.00\",\"18\":\"154\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"26\",\"22\":\"16500.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"176.6\",\"8\":\"66.2\",\"9\":\"54.3\",\"10\":\"2337\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"10.00\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"13950.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"99.4\",\"7\":\"176.6\",\"8\":\"66.4\",\"9\":\"54.3\",\"10\":\"2824\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.00\",\"18\":\"115\",\"19\":\"5500\",\"20\":\"18\",\"21\":\"22\",\"22\":\"17450.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.8\",\"7\":\"177.3\",\"8\":\"66.3\",\"9\":\"53.1\",\"10\":\"2507\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"15250.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.7\",\"10\":\"2844\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"17710.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.7\",\"10\":\"2954\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"25\",\"22\":\"18920.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"105.8\",\"7\":\"192.7\",\"8\":\"71.4\",\"9\":\"55.9\",\"10\":\"3086\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"131\",\"14\":\"mpfi\",\"15\":\"3.13\",\"16\":\"3.40\",\"17\":\"8.30\",\"18\":\"140\",\"19\":\"5500\",\"20\":\"17\",\"21\":\"20\",\"22\":\"23875.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"99.5\",\"7\":\"178.2\",\"8\":\"67.9\",\"9\":\"52.0\",\"10\":\"3053\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"131\",\"14\":\"mpfi\",\"15\":\"3.13\",\"16\":\"3.40\",\"17\":\"7.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"16\",\"21\":\"22\",\"22\":\"17859.17\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2395\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.50\",\"16\":\"2.80\",\"17\":\"8.80\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"16430.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2395\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.50\",\"16\":\"2.80\",\"17\":\"8.80\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"16925.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2710\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"20970.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"101.2\",\"7\":\"176.8\",\"8\":\"64.8\",\"9\":\"54.3\",\"10\":\"2765\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"21105.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"189.0\",\"8\":\"66.9\",\"9\":\"55.7\",\"10\":\"3055\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"164\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.19\",\"17\":\"9.00\",\"18\":\"121\",\"19\":\"4250\",\"20\":\"20\",\"21\":\"25\",\"22\":\"24565.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"189.0\",\"8\":\"66.9\",\"9\":\"55.7\",\"10\":\"3230\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"16\",\"21\":\"22\",\"22\":\"30760.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"103.5\",\"7\":\"193.8\",\"8\":\"67.9\",\"9\":\"53.7\",\"10\":\"3380\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"16\",\"21\":\"22\",\"22\":\"41315.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"110.0\",\"7\":\"197.0\",\"8\":\"70.9\",\"9\":\"56.3\",\"10\":\"3505\",\"11\":\"ohc\",\"12\":\"six\",\"13\":\"209\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.39\",\"17\":\"8.00\",\"18\":\"182\",\"19\":\"5400\",\"20\":\"15\",\"21\":\"20\",\"22\":\"36880.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"88.4\",\"7\":\"141.1\",\"8\":\"60.3\",\"9\":\"53.2\",\"10\":\"1488\",\"11\":\"l\",\"12\":\"three\",\"13\":\"61\",\"14\":\"2bbl\",\"15\":\"2.91\",\"16\":\"3.03\",\"17\":\"9.50\",\"18\":\"48\",\"19\":\"5100\",\"20\":\"47\",\"21\":\"53\",\"22\":\"5151.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1874\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"6295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"158.8\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1909\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"6575.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1876\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.41\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5572.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1876\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6377.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2128\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7957.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1967\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6229.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6692.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7609.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"2191\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8558.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"103.3\",\"7\":\"174.6\",\"8\":\"64.6\",\"9\":\"59.8\",\"10\":\"2535\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.34\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8921.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2811\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"mfi\",\"15\":\"3.60\",\"16\":\"3.90\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12964.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"86.6\",\"7\":\"144.6\",\"8\":\"63.9\",\"9\":\"50.8\",\"10\":\"1713\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.60\",\"18\":\"58\",\"19\":\"4800\",\"20\":\"49\",\"21\":\"54\",\"22\":\"6479.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"86.6\",\"7\":\"144.6\",\"8\":\"63.9\",\"9\":\"50.8\",\"10\":\"1819\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6855.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1837\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"79\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.07\",\"17\":\"10.10\",\"18\":\"60\",\"19\":\"5500\",\"20\":\"38\",\"21\":\"42\",\"22\":\"5399.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1940\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"6529.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"150.0\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"1956\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7129.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"163.4\",\"8\":\"64.0\",\"9\":\"54.5\",\"10\":\"2010\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.91\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"157.1\",\"8\":\"63.9\",\"9\":\"58.3\",\"10\":\"2024\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"1bbl\",\"15\":\"2.92\",\"16\":\"3.41\",\"17\":\"9.20\",\"18\":\"76\",\"19\":\"6000\",\"20\":\"30\",\"21\":\"34\",\"22\":\"7295.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"167.5\",\"8\":\"65.2\",\"9\":\"53.3\",\"10\":\"2236\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"7895.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"167.5\",\"8\":\"65.2\",\"9\":\"53.3\",\"10\":\"2289\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"9095.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"65.2\",\"9\":\"54.1\",\"10\":\"2304\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"8845.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"62.5\",\"9\":\"54.1\",\"10\":\"2372\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"1bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"86\",\"19\":\"5800\",\"20\":\"27\",\"21\":\"33\",\"22\":\"10295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"175.4\",\"8\":\"65.2\",\"9\":\"54.1\",\"10\":\"2465\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"mpfi\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.00\",\"18\":\"101\",\"19\":\"5800\",\"20\":\"24\",\"21\":\"28\",\"22\":\"12945.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.5\",\"7\":\"169.1\",\"8\":\"66.0\",\"9\":\"51.0\",\"10\":\"2293\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.58\",\"17\":\"9.10\",\"18\":\"100\",\"19\":\"5500\",\"20\":\"25\",\"21\":\"31\",\"22\":\"10345.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.3\",\"7\":\"170.7\",\"8\":\"61.8\",\"9\":\"53.5\",\"10\":\"2337\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"111\",\"14\":\"2bbl\",\"15\":\"3.31\",\"16\":\"3.23\",\"17\":\"8.50\",\"18\":\"78\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"29\",\"22\":\"6785.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1874\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"8916.50\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"155.9\",\"8\":\"63.6\",\"9\":\"52.0\",\"10\":\"1909\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.11\",\"17\":\"9.60\",\"18\":\"70\",\"19\":\"5400\",\"20\":\"38\",\"21\":\"43\",\"22\":\"8916.50\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"96.0\",\"7\":\"172.6\",\"8\":\"65.2\",\"9\":\"51.4\",\"10\":\"2734\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"119\",\"14\":\"spfi\",\"15\":\"3.43\",\"16\":\"3.23\",\"17\":\"9.20\",\"18\":\"90\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11048.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"113.0\",\"7\":\"199.6\",\"8\":\"69.6\",\"9\":\"52.8\",\"10\":\"4066\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"258\",\"14\":\"mpfi\",\"15\":\"3.63\",\"16\":\"4.17\",\"17\":\"8.10\",\"18\":\"176\",\"19\":\"4750\",\"20\":\"15\",\"21\":\"19\",\"22\":\"32250.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"113.0\",\"7\":\"199.6\",\"8\":\"69.6\",\"9\":\"52.8\",\"10\":\"4066\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"258\",\"14\":\"mpfi\",\"15\":\"3.63\",\"16\":\"4.17\",\"17\":\"8.10\",\"18\":\"176\",\"19\":\"4750\",\"20\":\"15\",\"21\":\"19\",\"22\":\"35550.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.0\",\"7\":\"191.7\",\"8\":\"70.6\",\"9\":\"47.8\",\"10\":\"3950\",\"11\":\"ohcv\",\"12\":\"twelve\",\"13\":\"326\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"2.76\",\"17\":\"11.50\",\"18\":\"262\",\"19\":\"5000\",\"20\":\"13\",\"21\":\"17\",\"22\":\"36000.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1890\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"30\",\"21\":\"31\",\"22\":\"5195.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1900\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6095.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"159.1\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1905\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6795.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"166.8\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1945\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.03\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6695.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.1\",\"7\":\"166.8\",\"8\":\"64.2\",\"9\":\"54.1\",\"10\":\"1950\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"91\",\"14\":\"2bbl\",\"15\":\"3.08\",\"16\":\"3.15\",\"17\":\"9.00\",\"18\":\"68\",\"19\":\"5000\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7395.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"53.7\",\"10\":\"2385\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"8845.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2410\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"8495.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"53.7\",\"10\":\"2385\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"10595.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2410\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"10245.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"98.8\",\"7\":\"177.8\",\"8\":\"66.5\",\"9\":\"55.5\",\"10\":\"2425\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.39\",\"16\":\"3.39\",\"17\":\"8.60\",\"18\":\"84\",\"19\":\"4800\",\"20\":\"26\",\"21\":\"32\",\"22\":\"11245.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.9\",\"7\":\"175.0\",\"8\":\"66.1\",\"9\":\"54.4\",\"10\":\"2670\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"140\",\"14\":\"mpfi\",\"15\":\"3.76\",\"16\":\"3.16\",\"17\":\"8.00\",\"18\":\"120\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"27\",\"22\":\"18280.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"115.6\",\"7\":\"202.6\",\"8\":\"71.7\",\"9\":\"56.5\",\"10\":\"3740\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"234\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.10\",\"17\":\"8.30\",\"18\":\"155\",\"19\":\"4750\",\"20\":\"16\",\"21\":\"18\",\"22\":\"34184.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"96.6\",\"7\":\"180.3\",\"8\":\"70.5\",\"9\":\"50.8\",\"10\":\"3685\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"234\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.10\",\"17\":\"8.30\",\"18\":\"155\",\"19\":\"4750\",\"20\":\"16\",\"21\":\"18\",\"22\":\"35056.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"120.9\",\"7\":\"208.1\",\"8\":\"71.7\",\"9\":\"56.7\",\"10\":\"3900\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"308\",\"14\":\"mpfi\",\"15\":\"3.80\",\"16\":\"3.35\",\"17\":\"8.00\",\"18\":\"184\",\"19\":\"4500\",\"20\":\"14\",\"21\":\"16\",\"22\":\"40960.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"112.0\",\"7\":\"199.2\",\"8\":\"72.0\",\"9\":\"55.4\",\"10\":\"3715\",\"11\":\"ohcv\",\"12\":\"eight\",\"13\":\"304\",\"14\":\"mpfi\",\"15\":\"3.80\",\"16\":\"3.35\",\"17\":\"8.00\",\"18\":\"184\",\"19\":\"4500\",\"20\":\"14\",\"21\":\"16\",\"22\":\"45400.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.7\",\"7\":\"178.4\",\"8\":\"68.0\",\"9\":\"54.8\",\"10\":\"2910\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"140\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.12\",\"17\":\"8.00\",\"18\":\"175\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16503.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5389.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"1944\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6189.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"64.4\",\"9\":\"50.8\",\"10\":\"2004\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6669.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.0\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2145\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"spdi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7689.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"173.0\",\"8\":\"65.4\",\"9\":\"49.4\",\"10\":\"2370\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9959.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"173.0\",\"8\":\"65.4\",\"9\":\"49.4\",\"10\":\"2328\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"8499.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2833\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.58\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12629.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2921\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"14869.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2926\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"14489.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2365\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"6989.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2405\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"25\",\"21\":\"32\",\"22\":\"8189.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2403\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9279.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.3\",\"7\":\"172.4\",\"8\":\"65.4\",\"9\":\"51.6\",\"10\":\"2403\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"110\",\"14\":\"spdi\",\"15\":\"3.17\",\"16\":\"3.46\",\"17\":\"7.50\",\"18\":\"116\",\"19\":\"5500\",\"20\":\"23\",\"21\":\"30\",\"22\":\"9279.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1889\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"5499.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6649.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1938\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6849.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"170.2\",\"8\":\"63.8\",\"9\":\"53.5\",\"10\":\"2024\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7349.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1951\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7299.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.6\",\"8\":\"63.8\",\"9\":\"53.3\",\"10\":\"2028\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7799.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.3\",\"8\":\"63.8\",\"9\":\"54.5\",\"10\":\"1971\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7499.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"170.2\",\"8\":\"63.8\",\"9\":\"53.5\",\"10\":\"2037\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"7999.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.1\",\"7\":\"162.4\",\"8\":\"63.8\",\"9\":\"53.3\",\"10\":\"2008\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.15\",\"16\":\"3.29\",\"17\":\"9.40\",\"18\":\"69\",\"19\":\"5200\",\"20\":\"31\",\"21\":\"37\",\"22\":\"8249.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"173.4\",\"8\":\"65.2\",\"9\":\"54.7\",\"10\":\"2324\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"120\",\"14\":\"2bbl\",\"15\":\"3.33\",\"16\":\"3.47\",\"17\":\"8.50\",\"18\":\"97\",\"19\":\"5200\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8949.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"173.4\",\"8\":\"65.2\",\"9\":\"54.7\",\"10\":\"2302\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"120\",\"14\":\"2bbl\",\"15\":\"3.33\",\"16\":\"3.47\",\"17\":\"8.50\",\"18\":\"97\",\"19\":\"5200\",\"20\":\"27\",\"21\":\"34\",\"22\":\"9549.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"181.7\",\"8\":\"66.5\",\"9\":\"55.1\",\"10\":\"3095\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"22\",\"22\":\"13499.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"184.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"3296\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"22\",\"22\":\"14399.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"184.6\",\"8\":\"66.5\",\"9\":\"55.1\",\"10\":\"3060\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"152\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"13499.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"91.3\",\"7\":\"170.7\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3071\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"17199.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"91.3\",\"7\":\"170.7\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3139\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"7.80\",\"18\":\"200\",\"19\":\"5200\",\"20\":\"17\",\"21\":\"23\",\"22\":\"19699.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"99.2\",\"7\":\"178.5\",\"8\":\"67.9\",\"9\":\"49.7\",\"10\":\"3139\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"181\",\"14\":\"mpfi\",\"15\":\"3.43\",\"16\":\"3.27\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"25\",\"22\":\"18399.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3020\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"11900.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"114.2\",\"7\":\"198.9\",\"8\":\"68.4\",\"9\":\"58.7\",\"10\":\"3230\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12440.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3075\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"2.19\",\"17\":\"8.40\",\"18\":\"95\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15580.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"114.2\",\"7\":\"198.9\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3285\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"2.19\",\"17\":\"8.40\",\"18\":\"95\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16695.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"107.9\",\"7\":\"186.7\",\"8\":\"68.4\",\"9\":\"56.7\",\"10\":\"3075\",\"11\":\"l\",\"12\":\"four\",\"13\":\"120\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.19\",\"17\":\"8.40\",\"18\":\"97\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"16630.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"108.0\",\"7\":\"186.7\",\"8\":\"68.3\",\"9\":\"56.0\",\"10\":\"3130\",\"11\":\"l\",\"12\":\"four\",\"13\":\"134\",\"14\":\"mpfi\",\"15\":\"3.61\",\"16\":\"3.21\",\"17\":\"7.00\",\"18\":\"142\",\"19\":\"5600\",\"20\":\"18\",\"21\":\"24\",\"22\":\"18150.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1918\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"37\",\"21\":\"41\",\"22\":\"5572.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2128\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"spdi\",\"15\":\"3.03\",\"16\":\"3.39\",\"17\":\"7.60\",\"18\":\"102\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"30\",\"22\":\"7957.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"50.6\",\"10\":\"1967\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6229.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"167.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"1989\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"90\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6692.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"167.3\",\"8\":\"63.8\",\"9\":\"50.8\",\"10\":\"2191\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"2.97\",\"16\":\"3.23\",\"17\":\"9.40\",\"18\":\"68\",\"19\":\"5500\",\"20\":\"31\",\"21\":\"38\",\"22\":\"7609.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"103.3\",\"7\":\"174.6\",\"8\":\"64.6\",\"9\":\"59.8\",\"10\":\"2535\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"2bbl\",\"15\":\"3.35\",\"16\":\"3.46\",\"17\":\"8.50\",\"18\":\"88\",\"19\":\"5000\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8921.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"95.9\",\"7\":\"173.2\",\"8\":\"66.3\",\"9\":\"50.2\",\"10\":\"2818\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"156\",\"14\":\"spdi\",\"15\":\"3.59\",\"16\":\"3.86\",\"17\":\"7.00\",\"18\":\"145\",\"19\":\"5000\",\"20\":\"19\",\"21\":\"24\",\"22\":\"12764.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.9\",\"8\":\"68.3\",\"9\":\"50.2\",\"10\":\"2778\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"151\",\"14\":\"mpfi\",\"15\":\"3.94\",\"16\":\"3.11\",\"17\":\"9.50\",\"18\":\"143\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"27\",\"22\":\"22018.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2756\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"32528.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2756\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"34028.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"rear\",\"6\":\"89.5\",\"7\":\"168.9\",\"8\":\"65.0\",\"9\":\"51.6\",\"10\":\"2800\",\"11\":\"ohcf\",\"12\":\"six\",\"13\":\"194\",\"14\":\"mpfi\",\"15\":\"3.74\",\"16\":\"2.90\",\"17\":\"9.50\",\"18\":\"207\",\"19\":\"5900\",\"20\":\"17\",\"21\":\"25\",\"22\":\"37028.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"175.7\",\"8\":\"72.3\",\"9\":\"50.5\",\"10\":\"3366\",\"11\":\"dohcv\",\"12\":\"eight\",\"13\":\"203\",\"14\":\"mpfi\",\"15\":\"3.94\",\"16\":\"3.11\",\"17\":\"10.00\",\"18\":\"288\",\"19\":\"5750\",\"20\":\"17\",\"21\":\"28\",\"22\":\"31400.50\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.1\",\"7\":\"181.5\",\"8\":\"66.5\",\"9\":\"55.2\",\"10\":\"2579\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"132\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.90\",\"17\":\"8.70\",\"18\":\"90\",\"19\":\"5100\",\"20\":\"23\",\"21\":\"31\",\"22\":\"9295.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"96.1\",\"7\":\"176.8\",\"8\":\"66.6\",\"9\":\"50.5\",\"10\":\"2460\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"132\",\"14\":\"mpfi\",\"15\":\"3.46\",\"16\":\"3.90\",\"17\":\"8.70\",\"18\":\"90\",\"19\":\"5100\",\"20\":\"23\",\"21\":\"31\",\"22\":\"9895.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2658\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.31\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"11850.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2695\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"12170.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2707\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"2.54\",\"16\":\"2.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"15040.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2758\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.30\",\"18\":\"110\",\"19\":\"5250\",\"20\":\"21\",\"21\":\"28\",\"22\":\"15510.00\"},{\"1\":\"turbo\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2808\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"26\",\"22\":\"18150.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"99.1\",\"7\":\"186.6\",\"8\":\"66.5\",\"9\":\"56.1\",\"10\":\"2847\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"121\",\"14\":\"mpfi\",\"15\":\"3.54\",\"16\":\"3.07\",\"17\":\"9.00\",\"18\":\"160\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"26\",\"22\":\"18620.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"156.9\",\"8\":\"63.4\",\"9\":\"53.7\",\"10\":\"2050\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"97\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.36\",\"17\":\"9.00\",\"18\":\"69\",\"19\":\"4900\",\"20\":\"31\",\"21\":\"36\",\"22\":\"5118.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"93.7\",\"7\":\"157.9\",\"8\":\"63.6\",\"9\":\"53.7\",\"10\":\"2120\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"8.70\",\"18\":\"73\",\"19\":\"4400\",\"20\":\"26\",\"21\":\"31\",\"22\":\"7053.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"93.3\",\"7\":\"157.3\",\"8\":\"63.8\",\"9\":\"55.7\",\"10\":\"2240\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"8.70\",\"18\":\"73\",\"19\":\"4400\",\"20\":\"26\",\"21\":\"31\",\"22\":\"7603.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2145\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.50\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"32\",\"21\":\"37\",\"22\":\"7126.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2190\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.50\",\"18\":\"82\",\"19\":\"4400\",\"20\":\"28\",\"21\":\"33\",\"22\":\"7775.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.2\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"52.5\",\"10\":\"2340\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"94\",\"19\":\"5200\",\"20\":\"26\",\"21\":\"32\",\"22\":\"9960.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"54.3\",\"10\":\"2385\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"25\",\"22\":\"9233.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"172.0\",\"8\":\"65.4\",\"9\":\"54.3\",\"10\":\"2510\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"7.70\",\"18\":\"111\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11259.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"173.5\",\"8\":\"65.4\",\"9\":\"53.0\",\"10\":\"2290\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"32\",\"22\":\"7463.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.0\",\"7\":\"173.5\",\"8\":\"65.4\",\"9\":\"53.0\",\"10\":\"2455\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"94\",\"19\":\"5200\",\"20\":\"25\",\"21\":\"31\",\"22\":\"10198.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"96.9\",\"7\":\"173.6\",\"8\":\"65.4\",\"9\":\"54.9\",\"10\":\"2420\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"2bbl\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"9.00\",\"18\":\"82\",\"19\":\"4800\",\"20\":\"23\",\"21\":\"29\",\"22\":\"8013.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"96.9\",\"7\":\"173.6\",\"8\":\"65.4\",\"9\":\"54.9\",\"10\":\"2650\",\"11\":\"ohcf\",\"12\":\"four\",\"13\":\"108\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"2.64\",\"17\":\"7.70\",\"18\":\"111\",\"19\":\"4800\",\"20\":\"23\",\"21\":\"23\",\"22\":\"11694.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"1985\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"35\",\"21\":\"39\",\"22\":\"5348.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"2040\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6338.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"158.7\",\"8\":\"63.6\",\"9\":\"54.5\",\"10\":\"2015\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"38\",\"22\":\"6488.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"2280\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"31\",\"21\":\"37\",\"22\":\"6918.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"2290\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"27\",\"21\":\"32\",\"22\":\"7898.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"4wd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"169.7\",\"8\":\"63.6\",\"9\":\"59.1\",\"10\":\"3110\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"92\",\"14\":\"2bbl\",\"15\":\"3.05\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"62\",\"19\":\"4800\",\"20\":\"27\",\"21\":\"32\",\"22\":\"8778.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"53.0\",\"10\":\"2081\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"30\",\"21\":\"37\",\"22\":\"6938.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2109\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"30\",\"21\":\"37\",\"22\":\"7198.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"53.0\",\"10\":\"2094\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"38\",\"21\":\"47\",\"22\":\"7738.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2122\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"34\",\"22\":\"8358.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"95.7\",\"7\":\"166.3\",\"8\":\"64.4\",\"9\":\"52.8\",\"10\":\"2140\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"28\",\"21\":\"34\",\"22\":\"9258.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2169\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8058.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2204\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"2bbl\",\"15\":\"3.19\",\"16\":\"3.03\",\"17\":\"9.00\",\"18\":\"70\",\"19\":\"4800\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8238.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2265\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.24\",\"16\":\"3.08\",\"17\":\"9.40\",\"18\":\"112\",\"19\":\"6600\",\"20\":\"26\",\"21\":\"29\",\"22\":\"9298.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"168.7\",\"8\":\"64.0\",\"9\":\"52.6\",\"10\":\"2300\",\"11\":\"dohc\",\"12\":\"four\",\"13\":\"98\",\"14\":\"mpfi\",\"15\":\"3.24\",\"16\":\"3.08\",\"17\":\"9.40\",\"18\":\"112\",\"19\":\"6600\",\"20\":\"26\",\"21\":\"29\",\"22\":\"9538.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2540\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"8449.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2536\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"9639.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2551\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"9989.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hardtop\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2679\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"11199.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"52.0\",\"10\":\"2714\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"11549.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"98.4\",\"7\":\"176.2\",\"8\":\"65.6\",\"9\":\"53.0\",\"10\":\"2975\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"146\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.50\",\"17\":\"9.30\",\"18\":\"116\",\"19\":\"4800\",\"20\":\"24\",\"21\":\"30\",\"22\":\"17669.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"54.9\",\"10\":\"2326\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"29\",\"21\":\"34\",\"22\":\"8948.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"53.9\",\"10\":\"2414\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"9988.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"54.9\",\"10\":\"2414\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"10898.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"102.4\",\"7\":\"175.6\",\"8\":\"66.5\",\"9\":\"53.9\",\"10\":\"2458\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"122\",\"14\":\"mpfi\",\"15\":\"3.31\",\"16\":\"3.54\",\"17\":\"8.70\",\"18\":\"92\",\"19\":\"4200\",\"20\":\"27\",\"21\":\"32\",\"22\":\"11248.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.9\",\"7\":\"183.5\",\"8\":\"67.7\",\"9\":\"52.0\",\"10\":\"2976\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.30\",\"18\":\"161\",\"19\":\"5200\",\"20\":\"20\",\"21\":\"24\",\"22\":\"16558.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"102.9\",\"7\":\"183.5\",\"8\":\"67.7\",\"9\":\"52.0\",\"10\":\"3016\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.30\",\"18\":\"161\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15998.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.5\",\"7\":\"187.8\",\"8\":\"66.5\",\"9\":\"54.1\",\"10\":\"3131\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"171\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.20\",\"18\":\"156\",\"19\":\"5200\",\"20\":\"20\",\"21\":\"24\",\"22\":\"15690.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.5\",\"7\":\"187.8\",\"8\":\"66.5\",\"9\":\"54.1\",\"10\":\"3151\",\"11\":\"dohc\",\"12\":\"six\",\"13\":\"161\",\"14\":\"mpfi\",\"15\":\"3.27\",\"16\":\"3.35\",\"17\":\"9.20\",\"18\":\"156\",\"19\":\"5200\",\"20\":\"19\",\"21\":\"24\",\"22\":\"15750.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2209\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"7975.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2212\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8195.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2275\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"85\",\"19\":\"5250\",\"20\":\"27\",\"21\":\"34\",\"22\":\"8495.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"97.3\",\"7\":\"171.7\",\"8\":\"65.5\",\"9\":\"55.7\",\"10\":\"2300\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"10.00\",\"18\":\"100\",\"19\":\"5500\",\"20\":\"26\",\"21\":\"32\",\"22\":\"9995.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"convertible\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"159.3\",\"8\":\"64.2\",\"9\":\"55.6\",\"10\":\"2254\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"90\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"29\",\"22\":\"11595.00\"},{\"1\":\"std\",\"2\":\"two\",\"3\":\"hatchback\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"94.5\",\"7\":\"165.7\",\"8\":\"64.0\",\"9\":\"51.4\",\"10\":\"2221\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"90\",\"19\":\"5500\",\"20\":\"24\",\"21\":\"29\",\"22\":\"9980.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"180.2\",\"8\":\"66.9\",\"9\":\"55.1\",\"10\":\"2661\",\"11\":\"ohc\",\"12\":\"five\",\"13\":\"136\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"8.50\",\"18\":\"110\",\"19\":\"5500\",\"20\":\"19\",\"21\":\"24\",\"22\":\"13295.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"fwd\",\"5\":\"front\",\"6\":\"100.4\",\"7\":\"183.1\",\"8\":\"66.9\",\"9\":\"55.1\",\"10\":\"2563\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"109\",\"14\":\"mpfi\",\"15\":\"3.19\",\"16\":\"3.40\",\"17\":\"9.00\",\"18\":\"88\",\"19\":\"5500\",\"20\":\"25\",\"21\":\"31\",\"22\":\"12290.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"2912\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"12940.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3034\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"13415.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"2935\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"24\",\"21\":\"28\",\"22\":\"15985.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3042\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"24\",\"21\":\"28\",\"22\":\"16515.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"56.2\",\"10\":\"3045\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.15\",\"17\":\"7.50\",\"18\":\"162\",\"19\":\"5100\",\"20\":\"17\",\"21\":\"22\",\"22\":\"18420.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"wagon\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"104.3\",\"7\":\"188.8\",\"8\":\"67.2\",\"9\":\"57.5\",\"10\":\"3157\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"130\",\"14\":\"mpfi\",\"15\":\"3.62\",\"16\":\"3.15\",\"17\":\"7.50\",\"18\":\"162\",\"19\":\"5100\",\"20\":\"17\",\"21\":\"22\",\"22\":\"18950.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"2952\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"23\",\"21\":\"28\",\"22\":\"16845.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.8\",\"9\":\"55.5\",\"10\":\"3049\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"8.70\",\"18\":\"160\",\"19\":\"5300\",\"20\":\"19\",\"21\":\"25\",\"22\":\"19045.00\"},{\"1\":\"std\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"3012\",\"11\":\"ohcv\",\"12\":\"six\",\"13\":\"173\",\"14\":\"mpfi\",\"15\":\"3.58\",\"16\":\"2.87\",\"17\":\"8.80\",\"18\":\"134\",\"19\":\"5500\",\"20\":\"18\",\"21\":\"23\",\"22\":\"21485.00\"},{\"1\":\"turbo\",\"2\":\"four\",\"3\":\"sedan\",\"4\":\"rwd\",\"5\":\"front\",\"6\":\"109.1\",\"7\":\"188.8\",\"8\":\"68.9\",\"9\":\"55.5\",\"10\":\"3062\",\"11\":\"ohc\",\"12\":\"four\",\"13\":\"141\",\"14\":\"mpfi\",\"15\":\"3.78\",\"16\":\"3.15\",\"17\":\"9.50\",\"18\":\"114\",\"19\":\"5400\",\"20\":\"19\",\"21\":\"25\",\"22\":\"22625.00\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Examine the data\n\n## Dimensions\n\nIf one checks the dimensions of the data, one gets the following results.\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-2_3b1714eeb06b606e216896627d76277e'}\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 181  22\n```\n:::\n:::\n\nThis means that the data contains 181 rows and 22 collumns.\n\n## Detailed look\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-3_9120f565ea23207d135a1d06df1fbb89'}\n::: {.cell-output .cell-output-stdout}\n```\n#>   aspiration         doornumber          carbody           drivewheel       \n#>  Length:181         Length:181         Length:181         Length:181        \n#>  Class :character   Class :character   Class :character   Class :character  \n#>  Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n#>                                                                             \n#>                                                                             \n#>                                                                             \n#>  enginelocation       wheelbase        carlength        carwidth    \n#>  Length:181         Min.   : 86.60   Min.   :141.1   Min.   :60.30  \n#>  Class :character   1st Qu.: 94.50   1st Qu.:166.3   1st Qu.:64.00  \n#>  Mode  :character   Median : 96.50   Median :173.0   Median :65.40  \n#>                     Mean   : 98.21   Mean   :173.3   Mean   :65.74  \n#>                     3rd Qu.:100.40   3rd Qu.:180.2   3rd Qu.:66.50  \n#>                     Max.   :120.90   Max.   :208.1   Max.   :72.30  \n#>    carheight       curbweight    enginetype        cylindernumber    \n#>  Min.   :47.80   Min.   :1488   Length:181         Length:181        \n#>  1st Qu.:52.00   1st Qu.:2122   Class :character   Class :character  \n#>  Median :53.70   Median :2410   Mode  :character   Mode  :character  \n#>  Mean   :53.58   Mean   :2521                                        \n#>  3rd Qu.:55.50   3rd Qu.:2910                                        \n#>  Max.   :59.80   Max.   :4066                                        \n#>    enginesize     fuelsystem          boreratio         stroke    \n#>  Min.   : 61.0   Length:181         Min.   :2.540   Min.   :2.07  \n#>  1st Qu.: 98.0   Class :character   1st Qu.:3.150   1st Qu.:3.08  \n#>  Median :120.0   Mode  :character   Median :3.310   Median :3.23  \n#>  Mean   :127.1                      Mean   :3.325   Mean   :3.23  \n#>  3rd Qu.:141.0                      3rd Qu.:3.590   3rd Qu.:3.40  \n#>  Max.   :326.0                      Max.   :3.940   Max.   :4.17  \n#>  compressionratio   horsepower       peakrpm        citympg     \n#>  Min.   : 7.000   Min.   : 48.0   Min.   :4200   Min.   :13.00  \n#>  1st Qu.: 8.500   1st Qu.: 70.0   1st Qu.:4800   1st Qu.:19.00  \n#>  Median : 9.000   Median : 95.0   Median :5200   Median :24.00  \n#>  Mean   : 8.848   Mean   :106.2   Mean   :5182   Mean   :24.85  \n#>  3rd Qu.: 9.400   3rd Qu.:116.0   3rd Qu.:5500   3rd Qu.:30.00  \n#>  Max.   :11.500   Max.   :288.0   Max.   :6600   Max.   :49.00  \n#>    highwaympg        price      \n#>  Min.   :16.00   Min.   : 5118  \n#>  1st Qu.:25.00   1st Qu.: 7609  \n#>  Median :30.00   Median : 9980  \n#>  Mean   :30.48   Mean   :12999  \n#>  3rd Qu.:34.00   3rd Qu.:16430  \n#>  Max.   :54.00   Max.   :45400\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Rows: 181\n#> Columns: 22\n#> $ aspiration       <chr> \"std\", \"std\", \"std\", \"std\", \"std\", \"std\", \"std\", \"std…\n#> $ doornumber       <chr> \"two\", \"two\", \"two\", \"four\", \"four\", \"two\", \"four\", \"…\n#> $ carbody          <chr> \"convertible\", \"convertible\", \"hatchback\", \"sedan\", \"…\n#> $ drivewheel       <chr> \"rwd\", \"rwd\", \"rwd\", \"fwd\", \"4wd\", \"fwd\", \"fwd\", \"fwd…\n#> $ enginelocation   <chr> \"front\", \"front\", \"front\", \"front\", \"front\", \"front\",…\n#> $ wheelbase        <dbl> 88.6, 88.6, 94.5, 99.8, 99.4, 99.8, 105.8, 105.8, 105…\n#> $ carlength        <dbl> 168.8, 168.8, 171.2, 176.6, 176.6, 177.3, 192.7, 192.…\n#> $ carwidth         <dbl> 64.1, 64.1, 65.5, 66.2, 66.4, 66.3, 71.4, 71.4, 71.4,…\n#> $ carheight        <dbl> 48.8, 48.8, 52.4, 54.3, 54.3, 53.1, 55.7, 55.7, 55.9,…\n#> $ curbweight       <dbl> 2548, 2548, 2823, 2337, 2824, 2507, 2844, 2954, 3086,…\n#> $ enginetype       <chr> \"dohc\", \"dohc\", \"ohcv\", \"ohc\", \"ohc\", \"ohc\", \"ohc\", \"…\n#> $ cylindernumber   <chr> \"four\", \"four\", \"six\", \"four\", \"five\", \"five\", \"five\"…\n#> $ enginesize       <dbl> 130, 130, 152, 109, 136, 136, 136, 136, 131, 131, 108…\n#> $ fuelsystem       <chr> \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi\", \"mpfi…\n#> $ boreratio        <dbl> 3.47, 3.47, 2.68, 3.19, 3.19, 3.19, 3.19, 3.19, 3.13,…\n#> $ stroke           <dbl> 2.68, 2.68, 3.47, 3.40, 3.40, 3.40, 3.40, 3.40, 3.40,…\n#> $ compressionratio <dbl> 9.00, 9.00, 9.00, 10.00, 8.00, 8.50, 8.50, 8.50, 8.30…\n#> $ horsepower       <dbl> 111, 111, 154, 102, 115, 110, 110, 110, 140, 160, 101…\n#> $ peakrpm          <dbl> 5000, 5000, 5000, 5500, 5500, 5500, 5500, 5500, 5500,…\n#> $ citympg          <dbl> 21, 21, 19, 24, 18, 19, 19, 19, 17, 16, 23, 23, 21, 2…\n#> $ highwaympg       <dbl> 27, 27, 26, 30, 22, 25, 25, 25, 20, 22, 29, 29, 28, 2…\n#> $ price            <dbl> 13495.00, 16500.00, 16500.00, 13950.00, 17450.00, 152…\n```\n:::\n:::\n\n\nAfter the use of *summary()* and *glimpse()*. One can deduct the following from the data.\n\nThe data contains data of type double <dbl> and character <chr>.\nThe data of type double are numeric variables, therefor it is possible to\nperform mathematical operations with them, which is also done during summary().\nHowever for factor variables (data of type character) it only counts the \noccurrences.\n\nFurthermore one can read the maxima and minima, as well as the certain mid values from the \nsummary. This is useful to get a feeling of the distribution of the data.\n\n# Linear Regression to determine relevant factors\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-4_f4f86489944bef620038ef5f70550f31'}\n\n```{.r .cell-code}\n# All data\nlmCarModelAll <- lm(price ~ ., data = df)\n#summary(lmCarModelAll)\nsprintf(\"Adjusted R^2: %.4f\", broom::glance(lmCarModelAll)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Adjusted R^2: 0.9264\"\n```\n:::\n\n```{.r .cell-code}\n# Data only significant with at least alpha <= 0.1\nlmCarModell_zero_one <- lm(price ~ aspiration + doornumber + carbody + enginelocation\n                           + carwidth + enginetype + cylindernumber+ enginesize\n                           + fuelsystem  + stroke + peakrpm, data = df)\n#summary(lmCarModell_zero_one)\nsprintf(\"Adjusted R^2: %.4f\", broom::glance(lmCarModell_zero_one)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Adjusted R^2: 0.9276\"\n```\n:::\n\n```{.r .cell-code}\n# Data only significant with at least alpha <= 0.01\nlmCarModell_zero_zero_one <- lm(price ~ aspiration + carbody + enginelocation\n                           + carwidth + enginetype + cylindernumber+ enginesize\n                           + stroke + peakrpm, data = df)\n#summary(lmCarModell_zero_zero_one)\nsprintf(\"Adjusted R^2: %.4f\", broom::glance(lmCarModell_zero_zero_one)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Adjusted R^2: 0.9259\"\n```\n:::\n\n```{.r .cell-code}\n# Data only significant with at least alpha <= 0.01 and no enginetype\nlmCarModell_selected <- lm(price ~ aspiration + carbody + enginelocation\n                                + carwidth + cylindernumber+ enginesize\n                                + stroke + peakrpm, data = df)\n#summary(lmCarModell_selected)\nsprintf(\"Adjusted R^2: %.4f\", broom::glance(lmCarModell_selected)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Adjusted R^2: 0.8893\"\n```\n:::\n\n```{.r .cell-code}\n# Data only significant with at least alpha <= 0.1 and no doornumber\nlmCarModell_noDoor <- lm(price ~ aspiration + carbody + enginelocation\n                           + carwidth + enginetype + cylindernumber+ enginesize\n                           + fuelsystem  + stroke + peakrpm, data = df)\n#summary(lmCarModell_noDoor)\nsprintf(\"Adjusted R^2: %.4f\", broom::glance(lmCarModell_noDoor)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Adjusted R^2: 0.9280\"\n```\n:::\n:::\n\n\nTo save space, only the adjusted R^2^  is displayed, if one wants to see the summary, one can do so by running the code and uncomment the *summary()* lines.\n\nTo get a good linear regression model, it was decided to start with all variables and slowly exclude variables with a small significants. Through this process, the best results were achived with following variables:\naspiration, carbody, enginelocation, carwidth, enginetype\ncylindernumber, enginesize, fuelsystem, stroke and peakrpm\n\nWith this variables one is able to achieve a adjusted R^2^ of 0.928\n\n# Choose one regressor\n\nThis journal chose enginesize\n\n## Explain data type and values it can take on\n\nenginesize is of the type <dbl>, which means it contains numeric values,\nwhich can have decimal points. However enginesize is in the dataframe only \nrepresented by integer values. Also it would make no sense for it to be negative.\n\n\n## Plot relationship between enginesize and price\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-5_8959e58cb4d0c2c0a3cef15f4debdf13'}\n::: {.cell-output-display}\n![](03_regression_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nIf one plots the enginesize in regard to the prize it can be seen that a bigger\nengine size correlates to an higher price and this correlation seems to be linear.\nSo increasing the engine size will, most likely result in a higher price and a\nsmaller engine size in a lower price.\n\n## Statistical significant\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-6_af444bfc8553c7d504e1b30e2fb843dd'}\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ aspiration + carbody + enginelocation + \n#>     carwidth + enginetype + cylindernumber + enginesize + fuelsystem + \n#>     stroke + peakrpm, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -5689.4 -1135.6  -167.9  1050.6  9559.7 \n#> \n#> Coefficients:\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -33093.398  11696.892  -2.829 0.005283 ** \n#> aspirationturbo        3235.549    629.441   5.140 8.16e-07 ***\n#> carbodyhardtop        -4445.436   1261.493  -3.524 0.000559 ***\n#> carbodyhatchback      -3652.463   1097.252  -3.329 0.001090 ** \n#> carbodysedan          -2801.655   1083.225  -2.586 0.010618 *  \n#> carbodywagon          -3366.899   1163.259  -2.894 0.004347 ** \n#> enginelocationrear     6685.578   2083.122   3.209 0.001617 ** \n#> carwidth                633.495    184.487   3.434 0.000764 ***\n#> enginetypedohcv       -6524.427   2916.466  -2.237 0.026706 *  \n#> enginetypel            2550.542   1346.819   1.894 0.060121 .  \n#> enginetypeohc          3605.833    825.070   4.370 2.26e-05 ***\n#> enginetypeohcf          306.358   1191.724   0.257 0.797464    \n#> enginetypeohcv        -6229.239   1082.598  -5.754 4.52e-08 ***\n#> cylindernumberfive   -11038.816   2458.346  -4.490 1.38e-05 ***\n#> cylindernumberfour   -11733.891   2312.831  -5.073 1.10e-06 ***\n#> cylindernumbersix     -6513.164   1709.745  -3.809 0.000200 ***\n#> cylindernumberthree   -5313.956   3696.374  -1.438 0.152560    \n#> cylindernumbertwelve -13471.683   2739.257  -4.918 2.21e-06 ***\n#> enginesize              147.232     14.184  10.380  < 2e-16 ***\n#> fuelsystem2bbl          -85.591    819.650  -0.104 0.916968    \n#> fuelsystemmfi         -3453.085   2431.905  -1.420 0.157642    \n#> fuelsystemmpfi          235.319    885.475   0.266 0.790782    \n#> fuelsystemspdi        -2582.827   1171.745  -2.204 0.028980 *  \n#> fuelsystemspfi          748.039   2315.280   0.323 0.747064    \n#> stroke                -4869.933    789.248  -6.170 5.69e-09 ***\n#> peakrpm                   2.416      0.525   4.601 8.68e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2165 on 155 degrees of freedom\n#> Multiple R-squared:  0.938,\tAdjusted R-squared:  0.928 \n#> F-statistic: 93.83 on 25 and 155 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIf one takes a look at the before found linear model, one can see that the\nengine size is statistical significant with an p-value less than alpha = 0.001.\nThe same can be seen by the linear model without variable selection.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}